# Generated by Django 3.0.8 on 2020-09-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=80, null=True)),
                ('Age', models.IntegerField(default=None, null=True)),
                ('Address', models.TextField(max_length=300, null=True)),
                ('Gender', models.CharField(max_length=30, null=True)),
                ('Specialization', models.CharField(max_length=80, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('Qualification', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
