# Generated by Django 3.0.8 on 2020-09-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200924_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('Prescription', models.TextField(max_length=800, null=True)),
                ('Appointment', models.DateField(null=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Treatments', to='Users.Doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Treatments', to='Users.Patient')),
            ],
        ),
    ]
