# Generated by Django 3.0.8 on 2020-09-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200924_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='Appointment',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Prescription',
            field=models.TextField(default=None, max_length=800, null=True),
        ),
    ]
