# Generated by Django 3.0.8 on 2020-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20200924_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='Disease',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
