# Generated by Django 3.0.8 on 2020-09-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_remove_treatment_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='Disease',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Patients', to='Users.Disease'),
            preserve_default=False,
        ),
    ]
