# Generated by Django 3.0.8 on 2020-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_auto_20200924_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/None', verbose_name=''),
        ),
    ]
