# Generated by Django 3.0.8 on 2020-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_auto_20200930_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='filepath',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
