# Generated by Django 3.0.8 on 2020-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_auto_20201001_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
