# Generated by Django 3.0.8 on 2020-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_treatment_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='Reports', to='Users.Doctor'),
        ),
    ]
