# Generated by Django 3.0.8 on 2020-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_delete_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='SymptomList',
            field=models.ManyToManyField(blank=True, null=True, to='Users.Symptom'),
        ),
    ]
