# Generated by Django 3.0.8 on 2020-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_auto_20201104_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='Doctors',
            field=models.ManyToManyField(blank=True, related_name='Reports', to='Users.Doctor'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='SymptomList',
            field=models.ManyToManyField(blank=True, to='Users.Symptom'),
        ),
    ]
