# Generated by Django 3.0.8 on 2020-11-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_auto_20201104_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='Specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Diseases', to='Users.Specialization'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Treatments', to='Users.Doctor'),
        ),
    ]
