# Generated by Django 3.0.8 on 2020-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0032_auto_20201111_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
