# Generated by Django 3.0.1 on 2020-11-15 15:47

import Users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0034_qna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='Appointment',
            field=models.DateField(blank=True, default=None, null=True, validators=[Users.validators.validate_date]),
        ),
    ]
