# Generated by Django 3.0.1 on 2020-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_auto_20201115_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Others', 'O')], default='F', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Others', 'O')], default='F', max_length=30, null=True),
        ),
    ]
