# Generated by Django 3.0.8 on 2020-12-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_auto_20201116_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='Doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Treatments', to='Users.Doctor'),
        ),
    ]
